/*	
 * topdev GmbH, erstellt am 20.01.2010 09:00
 *
 * $Author: Renato Fontes $
 * $Date: JJJJ-MM-TT HH:MM:SS $
 * $Rev: _ $
 * -------------------------------------------
 * $Workfile: (01) notifadm.V_SUBSCRIPTION_INFORMATION.sql $
 *
 */

if not exists ( select * from sysobjects where id = object_id('notifadm.V_SUBSCRIPTION_INFORMATION') and OBJECTPROPERTY(id, 'IsView') = 1)
begin
	exec( N'create view notifadm.V_SUBSCRIPTION_INFORMATION as select * from INFORMATION_SCHEMA.TABLES;' );
end
GO

alter view notifadm.V_SUBSCRIPTION_INFORMATION(
	SBPN_ID, SBPN_PARAMETERS, SBER_ID, USER_ID, DEVC_ID, SBTP_CODE, DEVC_ADDRESS,
	CMMD_CODE, SBTP_CONDITIONS, SBTP_FIELDS, SBTP_EMAILADR,	SBTP_EMAILCC, SBTP_EMAILBCC, SBTP_EMAILREPLYADR, 
	SBTP_EMAILSUB, SBTP_ISDYNAMICSUB, EVTP_CODE, EVTP_BTABLE, EVTP_IDBTABLE

) as

select 

SBPN.SBPN_ID, SBPN.SBPN_PARAMETERS, SBPN.SBER_ID,SBER.USER_ID, SBPN.DEVC_ID, SBPN.SBTP_CODE,
DEVC.DEVC_ADDRESS, DEVC.CMMD_CODE, SBTP.SBTP_CONDITIONS, SBTP.SBTP_FIELDS, SBTP.SBTP_EMAILADR, 
SBTP.SBTP_EMAILCC, SBTP.SBTP_EMAILBCC, SBTP_EMAILREPLYADR,SBTP.SBTP_EMAILSUB,SBTP_ISDYNAMICSUB, EVST.EVTP_CODE, 
EVTP.EVTP_BTABLE, EVTP.EVTP_IDBTABLE

from notifadm.IO_SUBSCRIPTION SBPN

join notifadm.IO_DEVICE DEVC on SBPN.DEVC_ID = DEVC.DEVC_ID
join notifadm.IO_SUBSCRIPTION_TYPE SBTP on SBPN.SBTP_CODE = SBTP.SBTP_CODE
join notifadm.IO_EVENT_SUBSCRIPTION_TYPE EVST on SBPN.SBTP_CODE = EVST.SBTP_CODE
join notifadm.IO_EVENT_TYPE EVTP on EVST.EVTP_CODE = EVTP.EVTP_CODE
join notifadm.IO_SUBSCRIBER SBER on SBPN.SBER_ID = SBER.SBER_ID

GO