/*	
 * topdev GmbH, erstellt am 15.01.2010 11:00
 *
 * $Author: Renato Fontes $
 * $Date: JJJJ-MM-TT HH:MM:SS $
 * $Rev: _ $
 * -------------------------------------------
 * $Workfile: (01) notifadm.IO_SUBSCRIPTION_TYPE.sql $
 *
 */

if exists ( select * from sysobjects where id = object_id('notifadm.IO_SUBSCRIPTION_TYPE') and OBJECTPROPERTY(id, 'IsTable') = 1)
begin
	GOTO createView;
--	drop table notifadm.IO_SUBSCRIPTION_TYPE;
end;

create table notifadm.IO_SUBSCRIPTION_TYPE(
	SBTP_ID				UDT_ID IDENTITY NOT FOR REPLICATION,


-->	
	SBTP_CODE			UDT_CODE	NOT NULL,
	SBTP_DECODE			UDT_DECODE	NOT NULL,
	SBTP_CONDITIONS		xml			NOT NULL,
	SBTP_FIELDS			xml			NOT NULL,
	SBTP_EMAILADR		nvarchar(255) NOT NULL,
	SBTP_EMAILCC		nvarchar(255) NULL,
	SBTP_EMAILBCC		nvarchar(255) NULL,
	SBTP_EMAILREPLYADR	nvarchar(255) NULL,
	SBTP_EMAILSUB		XML NOT NULL,
	SBTP_ISDYNAMICSUB		UDT_BOOLEAN NOT NULL,

--<			
	SBTP_USER			UDT_USER	NOT NULL,
	SBTP_PTS			UDT_PTS		NOT NULL,
	SBTP_#PTS			UDT_#PTS	NULL,	--as convert( nvarchar(23), SBTP_PTS, 121 ),
	SBTP_ID_INT			UDT_ID_0	NOT NULL,
	SBTP_UQID			UDT_UQID	NOT NULL ROWGUIDCOL,
	SBTP_KZ_FREIGABE	UDT_BOOLEAN	NOT NULL,
	SBTP_KZ_REPLIKATION	UDT_BOOLEAN	NOT NULL,
	SBTP_KZ_GELOESCHT	UDT_BOOLEAN	NOT NULL,

	CONSTRAINT PK_SBTP PRIMARY KEY CLUSTERED( SBTP_ID )
);

CREATE UNIQUE INDEX SBTP_IX_01_U ON notifadm.IO_SUBSCRIPTION_TYPE( SBTP_UQID );
CREATE UNIQUE INDEX SBTP_IX_O2_U ON notifadm.IO_SUBSCRIPTION_TYPE( SBTP_CODE );
CREATE INDEX		SBTP_IX_02	 ON notifadm.IO_SUBSCRIPTION_TYPE( SBTP_KZ_GELOESCHT );

createView:

if not exists ( select * from sysobjects where id = object_id('notifadm.T_SUBSCRIPTION_TYPE') and OBJECTPROPERTY(id, 'IsView') = 1)
begin
	exec( N'create view notifadm.T_SUBSCRIPTION_TYPE as select * from INFORMATION_SCHEMA.TABLES;' );
end
GO

alter view notifadm.T_SUBSCRIPTION_TYPE(
		SBTP_ID,

		SBTP_CODE,
		SBTP_DECODE,
		SBTP_CONDITIONS,
		SBTP_FIELDS,
		SBTP_EMAILADR,
		SBTP_EMAILCC,
		SBTP_EMAILBCC,
		SBTP_EMAILREPLYADR,
		SBTP_EMAILSUB,
		SBTP_ISDYNAMICSUB,

		SBTP_USER,
		SBTP_PTS,
		SBTP_#PTS

) as
select	SBTP_ID,

		SBTP_CODE,
		SBTP_DECODE,
		SBTP_CONDITIONS,
		SBTP_FIELDS,
		SBTP_EMAILADR,
		SBTP_EMAILCC,
		SBTP_EMAILBCC,
		SBTP_EMAILREPLYADR,
		SBTP_EMAILSUB,
		SBTP_ISDYNAMICSUB,

		SBTP_USER,
		SBTP_PTS,
		SBTP_#PTS

from	notifadm.IO_SUBSCRIPTION_TYPE
where	SBTP_KZ_GELOESCHT = 0;

GO
